spring.application.name=spring-security-demo
spring.datasource.url=jdbc:postgresql://localhost:5431/spring_security_demo
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.security.user.name=sayan
spring.security.user.password=sayan